### ISSUE TITLE
Can't authorise in google

### ISSUE THREAD

**Issue by DaoKakao** [prrvchr/OAuth2OOo#1]
Hello!
When i try to get access from libreoffice 6.3 to gdrive i get following errors:
1. When sending request to google for OAuth2OOo app allowance, the browser returns error [Missing required parameter 'scope']. If i add the scope string manually in the module's settings it replaces nonalphabetic symbols to hex codes. 
2. The module does not add the 'scope' part authomatically despite correct appropriate setting.
3. Finally i've replaced needed symbols manually in the URL and managed to register OAuth module in my google account, but no success opening the gdrive, the gdriveOOo plugin reports with 'nonexistent object' and 'nonexistant file' messageboxes

**Comment by prrvchr** [comment]
Hi DaoKakao,

I'm sorry to have waited so much before answering you, but I wanted to be sure to have a solution to the problem ...
In order to be able to integrate OAuth2 Provider that do not follow the recommendations of the standard (like Dropbox...), it was necessary to make customizable the HTTP request parameters for the authorization and the tokens.

This is now done, and the OAuth2 Provider have now two new properties:
- Authorization options: which is a Json string representing the options necessary for the request to obtain the authorization code.
- Token options: which is a string Json representing the options necessary for the request to get the tokens.

A new version has not been created, it is necessary to download and install the following version:
[https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt](url) with the label: > Muti provider ready

I close the issue, but do not hesitate to open a new one if necessary.
