### ISSUE TITLE
LibreOffice extension does not work

### ISSUE THREAD

**Issue by ita1sya** [prrvchr/OAuth2OOo#4]
Hi. I tryied to install the extension on the Libreoffice V. 6.0.7.3, but it doesn't work. Durign installation I receive an error message, even if the extension seems to be installed. Then I try to activate the extension and i get a lot of error. Every error attached. Could you please help me? Thanks kind rgds
![err_oauth2_1](https://user-images.githubusercontent.com/64146622/88790248-29846c80-d198-11ea-9131-d5b84813ae28.JPG)
![err_oauth2_2](https://user-images.githubusercontent.com/64146622/88790250-2a1d0300-d198-11ea-994d-4124475d1a5b.JPG)
![err_oauth2_3](https://user-images.githubusercontent.com/64146622/88790251-2ab59980-d198-11ea-831e-a5d0b413e4fc.JPG)
![err_oauth2_4](https://user-images.githubusercontent.com/64146622/88790252-2ab59980-d198-11ea-99ca-fad265c6718a.JPG)
![err_oauth2_5](https://user-images.githubusercontent.com/64146622/88790255-2ab59980-d198-11ea-9ee0-5d3b5383af9d.JPG)

**Comment by prrvchr** [comment]
Hi ita1sya,

It looks like the extension was renamed while downloading (I see OAuth2OOo (2).oxt)
Could you reinstall it by first renaming the extension file to its original name, namely OAuth2OOo.oxt.

I'm not sure it comes from that, but otherwise I don't see ...

Keep me informed...

**Comment by ita1sya** [comment]
Hi prrvchr. Done and the extension seems to work now. BTW, trying to use the wizard, it open the browser and i get this message
![err_oauth2_B1](https://user-images.githubusercontent.com/64146622/88896540-411c2d80-d24a-11ea-9b0e-ad90c0c75a96.JPG)
Thanks

**Comment by ita1sya** [comment]
ps: sorry was my language: "functionality sign in with google temporarily disabled for this app" and "this app has not yet been verified by google and therefore cannot use the google login feature"

**Comment by prrvchr** [comment]
It's weird, a long time ago Google had blocked the OAuth2OOo account, because I did not have at the time the Terms Of Use and Privacy Policy.
But there, I just created a new Google account and I can connect without problems ...
Before I report the bug to Google, could you try with another Google account and maybe give me your location?

**Comment by ita1sya** [comment]
I tryied again using the same account, I tryied also using another account as suggested (stefano.annicchiarico.consulting@gmail.com), getting back always the same error message as I reported above. Thank you for helping me. K Rgds

**Comment by prrvchr** [comment]
Ok, can you give me the scope you use?

**Comment by ita1sya** [comment]
Sure! E-mailing to some customers

Thanks

Stefano

**Comment by prrvchr** [comment]
Hi,

`Sure! E-mailing to some customers` 

As I said above, only Google Drive and Google Contact scopes are registered with Google.

Quite simply because for Google to validate a scope, it wants a video of the application that uses this scope (funny procedure), and since the application that is supposed to use this scope is not yet finished, so this scope is not yet usable (although it appears in the list of scopes)

I'm sorry but you'll have to wait a bit ... (in a few months smtpMailerOOo will be available)
