### ISSUE TITLE
Problems in 7.3

### ISSUE THREAD

**Issue by mj8w** [prrvchr/OAuth2OOo#9]
I am trying to perform a email mail merge in libreoffice 7.3.
I have performed the Oauth2 wizard in the extension manager, and that was successful.
I am using gmail.
In the mail merge menu, I am able to set up the merge, it prepares to send the emails, but never actually sends them. I'm not sure how to debug this.

**Comment by prrvchr** [comment]
Hi [mj8w](https://github.com/mj8w),

First of all thank you for taking the time to create an issue, this allows me to improve the quality of the extensions.

Although this problem was created in OAuth2OOo, I assume it concerns smtpMailerOOo.

To perform an email merge in smtpMailerOOo, you must:

- [Merge email to mailing list](https://github.com/prrvchr/smtpMailerOOo#merging-emails-to-mailing-lists)
- [**Start the spooler to send the mailing list**](https://github.com/prrvchr/smtpMailerOOo#outgoing-emails)

Normally it should work. If not, please let me know about messages appearing in the [spooler activity log](https://github.com/prrvchr/smtpMailerOOo#spooler-activity-log).

**Comment by prrvchr** [comment]
No answer, I'm closing
